version: '2.1'

networks:
  nod-newscrawler:

services:
  nodcore:
    image: uhhlt/nodcore
    volumes:
      - ${PWD}/out/nod/german:/app/content
    depends_on:
          db:
            condition: service_healthy
    networks:
      nod-newscrawler:

  nodweb:
    image: uhhlt/nodweb
    restart: always
    ports:
      - 10008:9000
    depends_on:
          db:
            condition: service_healthy
    networks:
      nod-newscrawler:

  db:
      image: mariadb
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=nodcore
        - MYSQL_USER=nod
        - MYSQL_PORT=3306
        - MYSQL_PASSWORD=nod
      volumes:
        - ${PWD}/nod-data/:/var/lib/mysql
        - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
      command: ["--character-set-server=utf8", "--collation-server=utf8_bin"]
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-pnod", "-unod"]
        interval: 20s
        timeout: 10s
        retries: 10
      networks:
        nod-newscrawler: