version: '2.1'
services:
  nodcore:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./content:/app/content

  nodweb:
    build: ../NoDWeb
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9000:9000

  db:
    image: mariadb
    restart: always
    volumes:
      - "nod_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: nod
      MYSQL_DATABASE: nodcore
      MYSQL_USER: nod
      MYSQL_PASSWORD: nod
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306

volumes:
  nod_data: